### ISSUE TITLE
Bug: The popup menu acts very flaky

### ISSUE THREAD

**Issue by HEmile** [hadynz/obsidian-sidekick#18]
This is so close to perfect! I'm loving it ^^ 
In the last update with the aliases, I think you changed the popup. However, it's now very hard to use: 

https://user-images.githubusercontent.com/1289165/154803804-92bf02ac-bc99-401d-904d-fdedd9aae261.mov

Clicking or hovering doesn't seem to reliably let me choose the option

**Comment by hadynz** [comment]
I definitely encountered this issue but thought it was just me. 

Will spend time getting to the bottom why this behaviour is happening and try to resolve.

**Comment by hadynz** [comment]
This should be fixed in [1.4.1][1].

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.4.1

**Comment by HEmile** [comment]
Thanks! I just tested but I'm still having the same behaviour in the main.js from the release

**Comment by hadynz** [comment]
Are you sure? Can you restart Obsidian after downloading the latest version? I was experiencing the same issue that you reported and now it is resolved for me.

**Comment by HEmile** [comment]
I already force reloaded yesterday, so yeah I'm sure. Can try again today but i doubt it. I think you mentioned it was sporadic but for me it's every time

**Comment by hadynz** [comment]
Yikes. Just saw that the fix was not included as I expected in the previous release.

Please try [1.4.3][1]. That should include the fix. 

[1]: https://github.com/hadynz/obsidian-sidekick/releases/tag/1.4.3

**Comment by HEmile** [comment]
Haha, I was wondering whether that would be the case. Works now!! Thank you so much :)
